language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - ./test.sh
env:
  - MOZ_HEADLESS=1 DEBUG=True SECRET_KEY=supersecrettraviskey DATABASE_URL=postgres:///travis_ci_test
addons:
  firefox: latest
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres