language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - ./test.sh
env:
  - PGPORT=5433 MOZ_HEADLESS=1 DEBUG=True SECRET_KEY=supersecrettraviskey DATABASE_URL=postgres:///travis_ci_test
addons:
  firefox: latest
services:
  postgresql:  "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres