# Generated by Django 2.1.3 on 2018-11-02 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20181101_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='referee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='refereed_games', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
